AWSTemplateFormatVersion: 2010-09-09
Description: >-
  seneca-stats

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 15
    Runtime: nodejs12.x
    MemorySize: 128

Resources:
  GetSessionStats:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getSessionStats
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StatsTable
      Environment:
        Variables:
          STATS_TABLE: !Ref StatsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /courses/{courseId}/sessions/{sessionId}
            Method: GET

  GetCourseStats:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getCourseStats
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StatsTable
      Environment:
        Variables:
          STATS_TABLE: !Ref StatsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /courses/{courseId}
            Method: GET

  PostSessionData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postSessionData
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StatsTable
      Environment:
        Variables:
          STATS_TABLE: !Ref StatsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /courses/{courseId}
            Method: POST

  StatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
